- name: Upload dist to cPanel
  uses: SamKirkland/FTP-Deploy-Action@v4.3.5
  with:
    server: ${{ secrets.CPANEL_HOST }}
    username: ${{ secrets.CPANEL_USER }}
    password: ${{ secrets.CPANEL_PASS }}
    protocol: ftps
    port: 21
    local-dir: dist/
    server-dir: public_html/
    dangerous-clean-slate: true